name: "[dispatch] all"
on:
  workflow_dispatch:
        
jobs:
  get_repos:
    runs-on: ubuntu-latest
    outputs:
      repos: ${{ steps.set_repos.outputs.repos }}
    steps:
      - name: Set repos JSON
        id: set_repos
        run: |
          QUERY="q=org:cloudforet-io+topic:core"
          TOKEN="${{ secrets.PAT+TOKEN  }}"
          API_URL="https://api.github.com/search/repositories"
          REPOS=$(curl -s -H "Authorization: token $token" "$API_URL?$QUERY" | jq -r '.[].full_name')
          echo 'repos:{\"repos\":$REPOS}' >> $GITHUB_OUTPUT
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ${{ fromJson(steps.get_repos.outputs.repos) }}
    steps:
      - name: Build
        run: |
          echo ${{ matrix.repo }}
