name: "[dispatch] all"
on:
  workflow_dispatch:
        
jobs:
  search-repositories:
    runs-on: ubuntu-latest
    steps:
      - name: Search repositories with GitHub API
        id: search-repositories
        uses: octokit/request-action@v2.x
        with:
          route: GET /search/repositories
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          INPUT_Q: 'org:GJ-playgroud+topic:core'
      - name: Set output variable
        id: set-output-variable
        run: |
          echo "result: ${{ steps.search-repositories.outputs.data }}"
          echo "repos=$(echo '${{ steps.search-repositories.outputs.data }}' | jq -r '.items[].full_name' | paste -sd "," -)" >> $GITHUB_OUTPUT
          

  echo:
    needs: ['search-repositories']
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo ${{ fromJson(needs.search-repositories.outputs.repos) }}
