name: "test"
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'input image tag `vx.y`'
        required: true

jobs:
  versioning:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.job1.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: echotest
        id: echo
        run: |
          git config user.email github-actions@github.com
          git config user.name github-actions
          git pull
          git add .
          git commit -m "Create New Tag ${{ github.event.inputs.tag }}"
          git tag ${{ github.event.inputs.tag }}
          git push --atomic origin master ${{ env.VERSION }}
