name: build-docker-image

on:
  push:
    tags:
      - v*

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Get Tag Version
      id: tag_version
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    
    - name: echo
      env:
        CURRUNT_TAG_VERSION: ${{ github.event.release.tag_name }}
      run: |
        echo ${{ steps.tag_version.outputs.tag }}
