name: "test"
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: false
        default: 'Mona the Octocat'

jobs:
  versioning:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.job1.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: echotest
        id: echo
        run: echo ${{ secrets.TEST }}
