name: ci
on:
  push:
    branches:
      - master
      
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "ya-ho!"
      - run: echo "${{ github.event_name }}"
