name: "[test] create branch"

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: branch name
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: create branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: '${{ github.event.inputs.branch_name }}'
