name: "[test] image scan"

on:
  workflow_dispatch:
    inputs:
      version:
        description: image version

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          # version: x.y.z
          platforms: linux/arm64, linux/amd64, linux/amd64/v2, linux/386, linux/arm/v7, linux/arm/v6

      - name: Login to Docker HUB
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and output into local
        run: docker buildx build . --platform linux/amd64,linux/arm64,linux/arm/v7 -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_APP_NAME }}:${{ github.event.inputs.version }} --output type=tar,dest=./output.tar

      - name: Import compressed docker image
        run: tar -c . | docker import - ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_APP_NAME }}:${{ github.event.inputs.version }}

      - name: Scan image
        uses: Azure/container-scan@v0
        with:
          image-name: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_APP_NAME }}:${{ github.event.inputs.version }}
          severity-threshold: LOW
          run-quality-checks: true

      # - name: Build and Push
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     platforms: linux/arm64, linux/amd64, linux/amd64/v2, linux/386, linux/arm/v7, linux/arm/v6
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_APP_NAME }}:${{ github.event.inputs.version }}
