name: "[test] image scan"

on:
  workflow_dispatch:
    inputs:
      version:
        description: image version
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # - name: Build and output into local
      #   run: docker buildx build . --platform linux/amd64,linux/arm64,linux/arm/v7 -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_APP_NAME }}:cache --output type=tar,dest=./output.tar

#       - name: Build and output into local
#         run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_APP_NAME }}:cache --output type=tar,dest=./output.tar .

#       - name: Import compressed docker image
#         run: tar -c output.tar | docker import - ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_APP_NAME }}:cache

      - name: Scan image
        uses: anchore/scan-action@v3
        with:
          image: spaceone/identity:1.11.0
          output-format: table
#           registry-username: ${{ secrets.DOCKERHUB_USERNAME }}
#           registry-password: ${{ secrets.DOCKERHUB_TOKEN }}

