name: "master_push_test"
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'input image tag `vx.y`'
        required: true

jobs:
  release-on-push:   
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v2 
          
      - name: Create a GitHub release 
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions@github.com
          git tag ${{ github.event.inputs.tag }} 
          git push origin "${{ github.event.inputs.tag }}"
