name: "[scan] trivy test"

on:
  workflow_dispatch:
    inputs:
      image:
        description: image name and version
        
env:
  SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: docker
        run: echo "This step will be implemeted docker build"
        
  scan:
    needs: docker
    runs-on: ubuntu-20.04
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ github.event.inputs.image }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
          
          
  notify:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: slack
        run: echo "this step will be implemented notify message to slack"
