name: "[scan] trivy test"

on:
  workflow_dispatch:
    inputs:
      image:
        description: image name and version
        
env:
  SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: docker
        run: echo "This step will be implemeted docker build"
  scan:
    needs: docker
    runs-on: ubuntu-20.04
    steps:
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ github.event.inputs.image }}
          format: 'table'
          output: /tmp/result.txt
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          
      - name: Set Result to ENV
        run: |
          echo "$(cat /tmp/result.txt) : ${{ vars.IMAGE_SCAN_RESULT }}"
          
      - name: slack
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":warning: Image vulnerability detected"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Image:*\n${{ github.event.inputs.image }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Detail:*\n${process.env.AS_WORKFLOW_RUN}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{secrets.VULNERABILITY_SLACK_WEBHOOK_URL}} 
          
  notify:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: slack
        run: echo "this step will be implemented notify message to slack"
