name: "slack test"

on:
  workflow_dispatch:
    inputs:
      image:
        description: image name and version
        
env:
  SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}}

jobs:
  slack:
    runs-on: ubuntu-latest
    steps:
    - uses: 8398a7/action-slack@v3
      with:
        status: ${{job.status}}
        author_name: Github Action Slack
        fields: repo
        custom_payload: |
          {
            text: "Custom Field Check",
            attachments: [{
              "author_name": "8398a7@action-slack", // json
              fallback: 'fallback',
              color: 'good',
              title: 'CI Result',
              text: 'Succeeded',
              fields: [{
                title: 'lower case',
                value: 'LOWER CASE CHECK'.toLowerCase(),
                short: true
              },
              {
                title: 'reverse',
                value: 'gnirts esrever'.split('').reverse().join(''),
                short: true
              },
              {
                title: 'long title1',
                value: 'long value1',
                short: false
              }],
              actions: [{
              }]
            }]
          }      
      env:
        SLACK_WEBHOOK_URL: ${{secrets.VULNERABILITY_SLACK_WEBHOOK_URL}} 
