name: "slack test"

on:
  workflow_dispatch:
    inputs:
      image:
        description: image name and version
        
env:
  SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}}

jobs:
  slack:
    runs-on: ubuntu-latest
    steps:
    - uses: 8398a7/action-slack@v3
      with:
        status: custom
        custom_payload: |
          {
            attachments: [{
              "author_name": Trivy Image Scanner
              color: 'warning',
              fields: [{
                title: 'lower case',
                value: 'LOWER CASE CHECK'.toLowerCase(),
                short: true
              },
              {
                title: 'reverse',
                value: 'gnirts esrever'.split('').reverse().join(''),
                short: true
              },
              {
                title: 'long title1',
                value: 'long value1',
                short: false
              }],
            }]
          }      
      env:
        SLACK_WEBHOOK_URL: ${{secrets.VULNERABILITY_SLACK_WEBHOOK_URL}} 
