name: "[Push] Sync CI"

on:
  push:
    branches:
      - master
    tags:
      - "v*.*"
    paths-ignore:
      - '.github/**'
      - 'src/VERSION'
  workflow_dispatch:

env:
  workflow_file_name: deploy.yaml
  owner: spaceone-dev
  repo: actions
  ref: master

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        if: ${{ github.event.ref }} =~ 'tags'
        run: echo ${{ github.event.ref }}
