name: test

on:
  workflow_dispatch:
    inputs:
      container_arch:
        type: choice
        description: 'enter version(x.y.z)'
        default: linux/amd64
        options:
        - "linux/amd64"
        - "linux/amd64,linux/arm64"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Print container_arch
        run: |
          echo ${{ github.event.inputs.container_arch }}
