name: "[Push] Sync CI"

on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'
      - 'src/VERSION'
  workflow_dispatch:

env:
  workflow_file_name: deploy.yaml
  owner: spaceone-dev
  repo: actions
  ref: master

jobs:
  master_push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: master_push
        run: echo "master_push"
  pull_workflows:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: git pull
        run: echo "pull_wf"
