name: "test"

on:
  workflow_dispatch:
    inputs:
      no-cache:
        type: boolean
        required: false
        default: true
        
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
    - name: version
      run: |
        echo ${{ github.event.inputs.no-cache }}
        
