name: "test"

on:
  workflow_dispatch:


jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        run: echo ${{ github.event.repository.name }}
