name: "test"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 1.0.0
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
    - name: version
      run: |
        echo "XY=$(echo ${{ github.event.inputs.version }} | cut -d'.' -f1-2)" >> $GITHUB_ENV
        
    - name: echo
      run: echo ${{ env.XY }}
