name: "test"

on:
  workflow_dispatch:
    inputs:
      image:
        description: image name and version
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Push artifacts to origin master
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: master
          commit_message: "[CI] api has been built"
          commit_user_name: GeunjeLEE
          commit_user_email: nigasa12@gmail.com
          commit_author: GeunjeLEE <nigasa12@gmail.com>
          push_options: '--force'
          tagging_message: v1.0.0
