name: Redis container example
on:
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: list
        run: |
          ls -la ./
          echo ${{ github.action_repository }}

