name: "[Push] Sync CI"

on:
  push:
    branches:
      - master
    tags:
      - "v*.*"
    paths-ignore:
      - '.github/**'
      - 'src/VERSION'
  workflow_dispatch:

env:
  workflow_file_name: deploy.yaml
  owner: spaceone-dev
  repo: actions
  ref: master

jobs:
  owner_check:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.repository_owner }}
  owner_check_2:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.repository_owner }}
  owner_check_3:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.repository_owner }}
  owner_check_4:
    runs-on: ubuntu-latest
    needs: owner_check_3
    steps:
      - run: echo ${{ github.repository_owner }}
  owner_check_5:
    runs-on: ubuntu-latest
    needs: owner_check_3
    steps:
      - run: echo ${{ github.repository_owner }}
  owner_check_6:
    runs-on: ubuntu-latest
    needs: owner_check_4
    steps:
      - run: echo ${{ github.repository_owner }}
  owner_check_7:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.repository_owner }}
