name: "test"

on:
  workflow_dispatch:
    inputs:
      image:
        description: image name and version
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
    - name: Copy
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.PAT_TOKEN }}
        src_path: dist/
        dst_path: /.
        dst_owner: GJ-playgroud
        dst_repo_name: plugin-test
