name: "[Push] Sync CI"

on:
  push:
    branches:
      - master
    tags:
      - "v*.*"
    paths-ignore:
      - '.github/**'
      - 'src/VERSION'
  workflow_dispatch:

env:
  workflow_file_name: deploy.yaml
  owner: spaceone-dev
  repo: actions
  ref: master

jobs:
  owner_check:
    if: github.repository_owner == 'GeunjeLE'
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.repository_owner }}
  echo:
    runs-on: ubuntu-latest
    needs: owner_check
    steps:
      - name: echo
        if: startsWith(github.ref, 'refs/tags')
        run: echo ${{ github.event.ref }}
