name: "test"

on:
  workflow_dispatch:
    inputs:
      image:
        description: image name and version
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: tagging
        run: |
          git tag v1.10.0
          git push origin v1.10.0 
