name: test

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'enter version(x.y.z)'
        required: true
        default: '1.0.0'

env:
  VERSION: ${{ github.event.inputs.version }}

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Get Date
        run: |
          sudo ln -sf /usr/share/zoneinfo/Asia/Seoul /etc/localtime
          CURRENT_TIME=$(date +'%Y%m%d.%H%M%S')
          
          echo "TIME=$CURRENT_TIME" >> $GITHUB_ENV
          echo "TIME=$CURRENT_TIME" >> $GITHUB_OUTPUT
          
      - name: print date
        run: echo ${{ env.TIME }}

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Get Date
        run: |
          echo ${{ needs.job1.outputs.TIME }}
