name: "test"

on:
  workflow_dispatch:
    inputs:
      image:
        description: image name and version
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo ${{ github.event.repository.name }}
