name: "trigger"

on:
  workflow_dispatch:
    inputs:
      trigger:
        description: 'test'
        required: true
        default: bang


jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: GeunjeLEE/circleci_test
          event-type: release
          client-payload: '{"tag": "${{ github.event.inputs.trigger }}"}'
